# Generated by Django 3.2.8 on 2021-10-10 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zips', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zip',
            old_name='contact_imform',
            new_name='contact_inform',
        ),
        migrations.RemoveField(
            model_name='zip',
            name='house_photo',
        ),
        migrations.AlterField(
            model_name='zip',
            name='house_adress',
            field=models.CharField(max_length=200, verbose_name='주소'),
        ),
        migrations.AlterField(
            model_name='zip',
            name='house_spec',
            field=models.CharField(max_length=200, verbose_name='스펙'),
        ),
    ]
