# Generated by Django 3.2.8 on 2021-10-26 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zips', '0002_auto_20211010_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='image/')),
                ('description', models.CharField(blank=True, max_length=100)),
                ('zip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zips.zip')),
            ],
        ),
    ]
