# Generated by Django 3.2.8 on 2021-10-26 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zips', '0003_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('zip', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='zips.zip')),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
