# Generated by Django 3.2.8 on 2021-10-28 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zips', '0004_auto_20211026_2238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='house_image',
            new_name='photo',
        ),
    ]
