# Generated by Django 3.2.8 on 2021-10-28 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zips', '0005_rename_house_image_photo_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='photo',
            new_name='house_image',
        ),
    ]
