# Generated by Django 3.2.8 on 2021-10-30 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zips', '0006_rename_photo_photo_house_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='zip',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
