# Generated by Django 3.2.8 on 2021-10-31 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zips', '0007_zip_main_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='zip',
            name='category',
            field=models.CharField(default='경기도', max_length=15),
        ),
    ]
