# Generated by Django 3.2.7 on 2021-11-06 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zips', '0008_zip_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='zip',
            name='created_by',
            field=models.CharField(max_length=80, null=True, verbose_name='작성자'),
        ),
    ]
