# Generated by Django 3.2.7 on 2021-12-08 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zips', '0012_auto_20211203_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='house_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='zip',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
