# Generated by Django 4.1.3 on 2022-12-12 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zips', '0015_rename_house_image_photo_sub_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='sub_image',
            new_name='house_image',
        ),
    ]
