# Generated by Django 4.1.3 on 2022-12-12 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zips', '0016_rename_sub_image_photo_house_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='house_image',
            new_name='sub_image',
        ),
        migrations.RenameField(
            model_name='zip',
            old_name='house_adress',
            new_name='house_address',
        ),
    ]
