# Generated by Django 4.1.3 on 2022-12-19 05:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zips', '0018_scrap'),
    ]

    operations = [
        migrations.AddField(
            model_name='zip',
            name='zip_likes',
            field=models.ManyToManyField(blank=True, related_name='zip_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Scrap',
        ),
    ]
