# Generated by Django 4.1.3 on 2022-12-19 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zips', '0020_remove_zip_zip_likes_scrap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrap',
            name='created_at',
        ),
    ]
